#!/usr/bin/env python

import os
assert os.system("python score.py valid_scorecards/tokens.yml") == 0
assert os.system("python score.py invalid_scorecards/double_pedestal.yml") != 0

print "tests passed!"
