#!/usr/bin/env python

import os

valid_cards = os.listdir('valid_scorecards')
for card in valid_cards:
    assert os.system("python score.py valid_scorecards/{0}".format(card)) == 0

invalid_cards = os.listdir('invalid_scorecards')
for card in invalid_cards:
    assert os.system("python score.py invalid_scorecards/{0}".format(card)) != 0

print "tests passed!"
